export const en = {
  appName: "Quiz King",
  appDescription: "Do you have what it takes to challenge the ultimate trivia master?",
  startChallenge: "Start the Challenge",
  chooseArena: "Choose Your Arena",
  selectCategory: "Select a category to begin the quiz.",
  generatingQuiz: "Generating a {category} quiz for you...",
  quizKingPreparing: "The Quiz King is preparing your challenge...",
  categoryLabel: "Category",
  questionLabel: "Question",
  youLabel: "You",
  quizKingLabel: "Quiz King",
  thinking: "Thinking...",
  quizKingChose: "The Quiz King chose: {answer}",
  nextQuestion: "Next Question",
  seeResults: "See Results",
  victoryTitle: "Victory!",
  victoryMessage: "You have defeated the Quiz King! Your knowledge is supreme.",
  defeatTitle: "So Close!",
  defeatMessage: "The Quiz King reigns supreme this time. Better luck next time!",
  drawTitle: "It's a Draw!",
  drawMessage: "An epic battle of wits ends in a tie. A worthy opponent indeed!",
  yourScore: "Your Score",
  quizKingScore: "Quiz King's Score",
  playAgain: "Play Again",
  errorGeneratingQuiz: "Sorry, there was an error generating the quiz. Please try another category or refresh.",
  loadingQuestion: "Loading question...",
  categories: {
    generalKnowledge: "General Knowledge",
    scienceNature: "Science & Nature",
    history: "History",
    geography: "Geography",
    moviesTV: "Movies & TV",
    music: "Music"
  }
};
