export const ja = {
  appName: "クイズ王",
  appDescription: "究極のトリビアマスターに挑戦する覚悟はできていますか？",
  startChallenge: "挑戦を始める",
  chooseArena: "アリーナを選択",
  selectCategory: "クイズを始めるカテゴリーを選んでください。",
  generatingQuiz: "{category}のクイズを生成中...",
  quizKingPreparing: "クイズ王があなたの挑戦を準備しています...",
  categoryLabel: "カテゴリー",
  questionLabel: "問題",
  youLabel: "あなた",
  quizKingLabel: "クイズ王",
  thinking: "考え中...",
  quizKingChose: "クイズ王の答え: {answer}",
  nextQuestion: "次の問題へ",
  seeResults: "結果を見る",
  victoryTitle: "勝利！",
  victoryMessage: "クイズ王を打ち負かしました！あなたの知識は最高です。",
  defeatTitle: "あと一歩！",
  defeatMessage: "今回はクイズ王の勝利です。次回頑張りましょう！",
  drawTitle: "引き分け！",
  drawMessage: "知恵比べは引き分けに終わりました。まさに好敵手！",
  yourScore: "あなたのスコア",
  quizKingScore: "クイズ王のスコア",
  playAgain: "もう一度プレイ",
  errorGeneratingQuiz: "申し訳ありません、クイズの生成中にエラーが発生しました。別のカテゴリを試すか、リフレッシュしてください。",
  loadingQuestion: "問題を読み込み中...",
  categories: {
    generalKnowledge: "一般知識",
    scienceNature: "科学と自然",
    history: "歴史",
    geography: "地理",
    moviesTV: "映画とテレビ",
    music: "音楽"
  }
};
